### ISSUE TITLE
Improve version management & avoid conflict between multiple version 

### ISSUE THREAD

**Issue by Taowyoo** [fortanix/rust-mbedtls#246]
## Purpose
To make it's possible to have multiple versions of `rust-mbedtls` in the dependency tree.

The following works need to be done:

### Able to compile together:
- [x] Add namespace for `mbedtls_malloc` to avoid conflicts. #243 
- [x] Move self test logic (including exclusive C function definitions and exported rust functions) to a separate crate #244 
- [ ] Move all platform specific exported function ( `threading` `time` `selftest` ) into a separate crate #254 
### Better version management:
- [x] Publish first version of `mbedtls-selftest`, done by #250 
- [x] Back-port all above changes to https://github.com/fortanix/rust-mbedtls/tree/v0.7, done by #251 
- [x] publish new version `0.7.3`
- [x] publish new version `0.8.2`
- [ ] back-port #254 to `v0.7`, #260 
- [ ] publish new version `0.7.4`
- [ ] back-port #254 to `v0.8`, #259 
- [ ] publish new version `0.8.3`

**Comment by Taowyoo** [comment]
Just realize that there also a lot of  rust functions and function pointers are exposed  in `lib.rs` and `threading.rs`.
They will also  cause conflict, those functions could be solved by following same path of self test but the function pointers might be difficult to deal with.

**Comment by jethrogb** [comment]
Yeah I guess we could make another crate mbedtls-platform-support. Especially for lib.rs I'm not sure if that will work properly for 0.7, because the features & conditional build logic supporting this changed pretty significantly in 0.8. I don't think the function pointers are a big deal, should work the same way?

**Comment by jethrogb** [comment]
> I'm not sure if that will work properly for 0.7

If it won't, then I think we should give up on this for now, possibly revert the mbedtls-selftest changes as well, and just do a flag day migration across all our projects.

**Comment by Taowyoo** [comment]
Got it, let me try if it's possible to split the code in 0.7
